---
title: "MyWebsite"
author: "mdd"
date: "November 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
OceanAK <- read.csv("C://Users//mddonnellan//Documents//R//Development//SASAP_examples//knb.92020.1.csv", stringsAsFactors = FALSE)

```

Load Packages
```{r, echo = FALSE}
suppressPackageStartupMessages({
library(tidyr)
library(dplyr)
library(leaflet)
library(ggplot2)
library(DT)
})

```

```{r}
#median annual escapement by species
median_esc <- OceanAK %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, Location, Year) %>% 
  summarize(OceanAK = sum(DailyCount, na.rm = TRUE)) %>% 
  group_by(Species) %>% 
  summarize(median_escapement = median(OceanAK))

median_esc

```

```{r}
ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()

```

```{r}
datatable(median_esc)

```

```{r}
locations <- OceanAK %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~ -abs(Longitude), ~ Latitude, popup = ~ Location)
```

